# Generated by Django 5.0 on 2023-12-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=75)),
                ('major', models.CharField(max_length=75)),
                ('student_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('signup_date', models.DateField()),
                ('print_date', models.DateField()),
                ('terms', models.JSONField()),
                ('grad_year', models.CharField(max_length=4)),
            ],
        ),
    ]
