# Generated by Django 5.0 on 2023-12-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bip_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
