# Generated by Django 5.0 on 2024-01-02 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bip_api', '0002_yearindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('karne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bip_api.karne')),
                ('terms', models.JSONField()),
            ],
        ),
    ]
